### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-rudra#136]
https://github.com/fabric8-analytics/fabric8-analytics-rudra/blob/64b4af7bb9c00b23a54a40c8e496921670d6d57c/rudra/deployments/emr_scripts/npm_emr.py#L30

**Comment by lucky-suman** [comment]
It's done and got merged also https://github.com/fabric8-analytics/fabric8-analytics-rudra/pull/137
